### ISSUE TITLE
Dockerfile isn't works anymore

### ISSUE THREAD

**Issue by dontturnaway** [devopsjourney1/jenkins-101#22]
When you build [Dockerfile](https://github.com/devopsjourney1/jenkins-101/blob/master/Dockerfile) provided, an error occurs: 
`#0 0.559 Package docker-ce is not available, but is referred to by another package.
#0 0.559 This may mean that the package is missing, has been obsoleted, or
#0 0.559 is only available from another source
#0 0.559 
#0 0.559 Package docker-ce-cli is not available, but is referred to by another package.
#0 0.559 This may mean that the package is missing, has been obsoleted, or
#0 0.559 is only available from another source`

**Comment by devopsjourney1** [comment]
Thanks I will look into if I can correct this or if anyone has the image available in a registry.

I guess the lesson to be learned here is to always send docker images to a registry!

**Comment by devopsjourney1** [comment]
Hey I couldn't recreate the issue but I heard others mention a similar problem. Since I was able to build the image using my PC I have uploaded it to a registry for everyone to use.  The below commands should get you the image and rename it to be consistent with the lab/video.

```docker pull devopsjourney1/jenkins-blueocean:2.332.3-1 && docker tag devopsjourney1/jenkins-blueocean:2.332.3-1 myjenkins-blueocean:2.332.3-1```
